version: "1.0"
name: "fargate-check-compose"

services:
  reverse-proxy-nginx:
    build:
      context: ..
      dockerfile: dockerfiles/Nginx.Dockerfile
    ports:
      - "80:80"
    restart: always
  django-app:
    env_file:
      - .env.docker
    build:
      context: ..
      dockerfile: dockerfiles/Django.Dockerfile
    expose:
      - "8000"
    restart: always
  postgres:
    image: postgres:14.3
    restart: always
    expose:
      - "5432"
    env_file:
        - .env.docker
    environment:
      - TZ=Asia/Seoul
